// The sequence of triangle numbers is generated by 
// adding the natural numbers. So the 7th triangle 
// number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
// The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// What is the value of the first triangle number to have 
// over five hundred divisors?

function triangulate(num) {
    var count = 0;
    var sum = 0;
    var maxDivisors = 1;
    while (maxDivisors <= num) {
        var divisors = 1;
        for (var i = 1; i <= sum / 2; i++) {
            if (sum % i === 0) {
                console.log(sum + " " + i)
                // console.log("divisors");
                divisors++;
            }
            if (divisors > maxDivisors) {
                maxDivisors = divisors;
            }
        }

        if (maxDivisors > num) {
            console.log("new sum " + sum);
        } else {
            sum += count;
            count++;
        }

    }
    console.log(sum);
}

triangulate(500);